spring:
  application:
    name: book_managerment

datasource:
  url: jdbc:postgresql://localhost:5432/library_db
  username: postgres
  password: "1234"
  driver-class-name: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true  # sql 쿼리를 콘솔에 보여주는 편리한 옵션

